circulation: fix create new loan request
inveniosoftware/invenio-app-ils pull request #142
Opened 2019-01-29 12:48 UTC by zzacharo

2019-01-29 12:51 UTC, topless requested changes

2019-01-29 12:51 UTC, topless commented on invenio_app_ils/circulation/utils.py
>      """Retrieve items given a document."""
The description does not match with what it actually returns

2019-01-29 13:16 UTC, kpsherva submitted a review, later dismissed

2019-01-29 14:33 UTC, zzacharo commented on invenio_app_ils/circulation/utils.py
> +    if item and item.get("document") and item["document"].get("document_pid"):
true I will change it ;)

2019-01-29 15:26 UTC, topless approved these changes

2019-01-30 20:09 UTC, ntarocco approved these changes
Thank you for fixing this!

2019-01-30 20:09 UTC, ntarocco commented on invenio_app_ils/circulation/api.py
> +            params["document_pid"] = document_pid
should we actually fail if `None`?

2019-01-31 08:30 UTC, merged