common-api: fix for getting response
inveniosoftware/invenio-app-ils pull request #206
Opened 2019-03-13 10:31 UTC by vladbmihaescu

Fix for getting the correct response.

2019-03-13 10:56 UTC, equadon requested changes

2019-03-13 10:56 UTC, equadon commented on invenio_app_ils/ui/src/invenio_app_ils/common/api/documents/document.js
> -    const totalHits = response.data.hits.total;
`totalHits` is undefined on line 52 now so maybe just keep the variable definition here?

2019-03-13 10:56 UTC, equadon commented on invenio_app_ils/ui/src/invenio_app_ils/common/api/loans/loan.js
> -    const totalHits = response.data.hits.total;
Same as in `document.js` :)

2019-03-13 14:09 UTC, equadon submitted a review, later dismissed

2019-03-15 12:58 UTC, topless submitted a review, later dismissed

2019-03-15 14:19 UTC, closed without merging