Records Editor integration, closes #13
inveniosoftware/invenio-app-ils pull request #32
Opened 2018-10-11 14:59 UTC by topless

Integration of the invenio-records-editor module.

2018-10-11 16:01 UTC, ntarocco approved these changes

2018-10-11 16:01 UTC, ntarocco requested changes
You are missing the dependency `invenio-records-editor`, and maybe add it also the requirements file.

2018-10-12 13:56 UTC, ntarocco reviewed
Can you please squash all commits to keep only 1 and remove the merge commits?
We can always squash when merging eventually.

2018-10-12 13:56 UTC, ntarocco commented on invenio_app_ils/ext.py
> +        _editor_blueprint = create_editor_blueprint(app)
Can you please remove this due to: https://github.com/inveniosoftware/invenio-records-editor/pull/5

2018-10-12 13:56 UTC, ntarocco commented on setup.py
> +    "invenio-records-editor==1.0.0a1"
Can you please `==1.0.0a2`

2018-10-12 14:16 UTC, topless commented
Mr. polite @ntarocco I think I covered everything, please be kind enough to let me know if there is anything else I can help you with. I wish you a great day and even greater weekend. May the horse be with you.

2018-10-12 14:31 UTC, ntarocco approved these changes

2018-10-12 14:31 UTC, merged