global: removed all `_` from js
inveniosoftware/invenio-app-ils pull request #352
Opened 2019-05-27 15:54 UTC by topless

2019-05-28 08:02 UTC, kpsherva submitted a review, later dismissed

2019-05-28 08:02 UTC, equadon requested changes

2019-05-28 08:02 UTC, equadon commented on invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/DocumentsDetails/components/DocumentMetadata/DocumentMetadata.js
> +  render_book_info() {
```suggestion
  renderBookInfo() {
```
This file had a few other instances of snake case.

2019-05-29 15:11 UTC, equadon approved these changes

2019-05-29 15:43 UTC, kpsherva approved these changes

2019-05-29 15:43 UTC, merged