Frontsite add electronic items
inveniosoftware/invenio-app-ils pull request #400
Opened 2019-06-26 15:30 UTC by vladbmihaescu

Add electronic items to Frontsite UI.
![Screenshot from 2019-06-26 17-28-44](https://user-images.githubusercontent.com/47737538/60193509-1639fb80-9838-11e9-8cea-b2f9115550a5.png)
![Screenshot from 2019-06-26 17-28-33](https://user-images.githubusercontent.com/47737538/60193517-176b2880-9838-11e9-9692-8012d86c0197.png)

(Closes #314)

2019-06-27 12:17 UTC, kprzerwa commented on invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/DocumentsDetails/components/DocumentMetadata/DocumentMetadata.js
> +            disabled={!eitems[0].open_access}
if it is not open access you should filter it out when fetching/serializing

2019-06-27 12:17 UTC, kprzerwa commented on invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/utils.js
> +export const prepareEItems = eitems => {
you could move it to serializers

2019-06-28 08:34 UTC, kpsherva requested changes

2019-06-28 08:34 UTC, kprzerwa commented on invenio_app_ils/ui/src/invenio_app_ils/common/api/documents/serializer.js
> +function serializeDocuments(documents) {
This serializer should be merged with the one above instead of creating new one - if needed. Let's discuss it.

2019-07-05 17:37 UTC, ntarocco commented
@kprzerwa @zzacharo @vladbmihaescu PR ready, to be squashed when merging.

2019-07-08 07:00 UTC, zzacharo submitted a review, later dismissed

2019-07-08 07:13 UTC, kprzerwa commented on invenio_app_ils/ui/src/invenio_app_ils/pages/frontsite/Home/components/MostRecentBooks/MostRecentBooks.js
> +      return {
this is repeated, maybe we could merge it in one formatter function?

2019-07-08 12:02 UTC, merged